# Generated by Django 2.0.4 on 2018-04-07 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(verbose_name='Дата и время')),
                ('article_likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('users_likes', models.ManyToManyField(related_name='users_article_main', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
                ('comments_date', models.DateTimeField()),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
