# Generated by Django 2.0.4 on 2018-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comments_comments_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
