# Generated by Django 2.0.4 on 2018-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='', upload_to='media/article/%Y/%m/%d', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
