# Generated by Django 2.0.4 on 2018-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20180410_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='static/article/images/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
