# Generated by Django 2.0.4 on 2018-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20180411_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
