# Generated by Django 2.0.4 on 2018-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20180411_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_published',
            field=models.BooleanField(default=True),
        ),
    ]
