# Generated by Django 2.0.4 on 2018-04-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_img_article',
            new_name='image_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
