# Generated by Django 2.0.4 on 2018-04-15 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20180413_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст статьи'),
        ),
    ]
