# Generated by Django 2.0.4 on 2018-04-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20180413_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_video',
        ),
    ]
