# Generated by Django 2.0.4 on 2018-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_remove_article_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_start_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Начальная картинка'),
        ),
    ]
