# Generated by Django 2.0.4 on 2018-04-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_article_article_start_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_article',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='Содержимое статьи'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
