# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 16:56
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('article', '0034_auto_20180416_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
